module.exports = {
CATEGORY_100: 'Bars and Restaurants',
CATEGORY_101: 'Bars',
CATEGORY_102: 'Billiard Clubs',
CATEGORY_103: 'Nachtclubs',
CATEGORY_104: 'Pubs, Biergaerten',
CATEGORY_105: 'Rockclubs',
CATEGORY_106: 'Tanzclubs',
CATEGORY_107: 'Karaokeclubs',
CATEGORY_200: 'Einkaufen',
CATEGORY_201: 'Innenausstattung',
CATEGORY_202: 'Buchhandlung',
CATEGORY_203: 'Spielzeuglaeden',
CATEGORY_204: 'Kinderbekleidungslaeden',
CATEGORY_205: 'Umstandsmode',
CATEGORY_206: 'Teppichgeschaefte',
CATEGORY_207: 'Computergeschaefte',
CATEGORY_208: 'Kosmetik',
CATEGORY_209: 'Moebelgeschaefte',
CATEGORY_210: 'Musikinstrumente',
CATEGORY_211: 'Unterwaeschegeschaeft',
CATEGORY_212: 'Schuhgeschaefte',
CATEGORY_213: 'Bekleidungsgeschaefte',
CATEGORY_214: 'Geschenklaeden',
CATEGORY_215: 'Geschirrlaeden',
CATEGORY_216: 'Fairtrade Geschaefte',
CATEGORY_217: 'Handtaschengeschaeft',
CATEGORY_218: 'Stofflaeden',
CATEGORY_219: 'Kamerageschaefte',
CATEGORY_220: 'Hours Shops',
CATEGORY_221: 'Eletronikgeschaefte und Haushaltsgerдte',
CATEGORY_222: 'Baumaerkte',
CATEGORY_223: 'Erwachsenengeschaefte',
CATEGORY_224: 'Trade centers',
CATEGORY_225: 'Juweliere',
CATEGORY_226: 'Sportgeschaefte',
CATEGORY_300: 'Restaurant and Cafe',
CATEGORY_301: 'Restaurant',
CATEGORY_302: 'Antikafe and coworking',
CATEGORY_303: 'Vegetarische Restaurants',
CATEGORY_304: 'Kindercafe',
CATEGORY_305: 'Fast',
CATEGORY_306: 'Kaffee',
CATEGORY_307: 'Pizza',
CATEGORY_308: 'Shisha',
CATEGORY_309: 'Tee',
CATEGORY_310: 'Japanische Restaurants',
CATEGORY_311: 'Cafe',
CATEGORY_400: 'Unterhaltung, Erholung',
CATEGORY_401: 'Zirkus',
CATEGORY_402: 'Parks',
CATEGORY_403: 'Kino',
CATEGORY_404: 'Zoos',
CATEGORY_405: 'Bowling',
CATEGORY_406: 'Saunen',
CATEGORY_407: 'Reiten',
CATEGORY_408: 'Wasserparks',
CATEGORY_409: 'Delphinarien',
CATEGORY_410: 'Konzerthallen',
CATEGORY_411: 'Strдnde',
CATEGORY_412: 'Tanzschulen',
CATEGORY_500: 'Sport und Freizeit',
CATEGORY_501: 'Schwimmen',
CATEGORY_502: 'Kampfsport',
CATEGORY_503: 'Reiten',
CATEGORY_504: 'Golfclubs',
CATEGORY_505: 'Skipisten',
CATEGORY_506: 'Yogacenter',
CATEGORY_507: 'Fitnessclub',
CATEGORY_508: 'Jachtclub',
CATEGORY_509: 'Fahrradverleih',
CATEGORY_510: 'Sportteil',
CATEGORY_511: 'Stadien',
CATEGORY_512: 'Fallschirmspringen',
CATEGORY_513: 'Paintball',
CATEGORY_514: 'Eisrutschbahnen',
CATEGORY_515: 'Kartfahren',
CATEGORY_600: 'Reparatur Dienstleistungen',
CATEGORY_601: 'Computer Dienstleistungen',
CATEGORY_602: 'Telefonreparatur',
CATEGORY_603: 'Appliance Repair',
CATEGORY_604: 'Musikinstrumentreparatur',
CATEGORY_605: 'Schuhreparatur',
CATEGORY_606: 'Sanitaer Dienstleistungen',
CATEGORY_607: 'Druckerreparatur, Patronenbefuellung',
CATEGORY_608: 'Fernsehgerдte Reparatur',
CATEGORY_609: 'Kamera Reparatur',
CATEGORY_610: 'Uhren Reparatur',
CATEGORY_611: 'Moebelrestaurierung',
CATEGORY_700: 'Auto',
CATEGORY_701: 'Ersatzteile und Zubehцr',
CATEGORY_702: 'Auto',
CATEGORY_703: 'Motor',
CATEGORY_704: 'Auto tuning',
CATEGORY_705: 'Schulen',
CATEGORY_706: 'Autoverleih',
CATEGORY_707: 'Reifen',
CATEGORY_708: 'Reifen und Raeder',
CATEGORY_709: 'Abtransport',
CATEGORY_800: 'Rechtsdienstleistungen',
CATEGORY_801: 'Anwaelte, Rechtsdienstleistungen',
CATEGORY_802: 'Notare',
CATEGORY_900: 'Drogerien',
CATEGORY_901: 'Andere Dienstleistungen',
CATEGORY_902: 'Kur',
CATEGORY_903: 'Designer',
CATEGORY_904: 'Manikueresalons',
CATEGORY_905: 'Massage',
CATEGORY_906: 'Haar',
CATEGORY_907: 'Piercing',
CATEGORY_908: 'Beauty',
CATEGORY_909: 'Sonnenstudios',
CATEGORY_910: 'Tattoo und Piercing Studio',
CATEGORY_1000: 'Pflanzen, Blumen',
CATEGORY_1001: 'Blumenlaeden',
CATEGORY_1002: 'Gartencenter',
CATEGORY_1100: 'Tiere',
CATEGORY_1101: 'Tierapotheke',
CATEGORY_1102: 'Tierklinik',
CATEGORY_1103: 'Haustier',
CATEGORY_1104: 'Liste',
CATEGORY_1105: 'Tierheim',
CATEGORY_1106: 'Tiersalon',
CATEGORY_1200: 'Kultur und Kunst',
CATEGORY_1201: 'Museum',
CATEGORY_1202: 'Darstellende Kьnste',
CATEGORY_1203: 'Buecherei',
CATEGORY_1204: 'Konzerte',
CATEGORY_1205: 'Kino',
CATEGORY_1206: 'Musik',
CATEGORY_1300: 'Aerzte',
CATEGORY_1301: 'Apotheken',
CATEGORY_1302: 'Zahnaerzte',
CATEGORY_1303: 'Psychologen',
CATEGORY_1304: 'Medical equipment',
CATEGORY_1305: 'Privatklinik',
CATEGORY_1306: 'Diagnostic Center',
CATEGORY_1307: 'Kliniken',
CATEGORY_1308: 'Krankenhaeuser',
CATEGORY_1309: 'Orientalische Medizin',
CATEGORY_1400: 'Bildung',
CATEGORY_1401: 'Universitaeten',
CATEGORY_1402: 'Hochschulen',
CATEGORY_1403: 'Kurse',
CATEGORY_1404: 'Musikschule',
CATEGORY_1405: 'Trainings und Seminare',
CATEGORY_1406: 'Kunstschule',
CATEGORY_1407: 'Schule',
CATEGORY_1500: 'Tourismus',
CATEGORY_1501: 'Visazentren',
CATEGORY_1502: 'Erholung',
CATEGORY_1503: 'Reiseveranstalter',
CATEGORY_1504: 'Reisebueros',

// Reports
REASON_100: 'Pornographie',
REASON_101: 'Spamming',
REASON_102: 'Missbraeuchliches Verhalten',
REASON_200: 'Missbrauch',
REASON_201: 'Erwachseneninhalte',
REASON_202: 'Drogenwerbung',
REASON_203: 'Kinderpornographie',
REASON_204: 'Gewalt / Extremismus',
REASON_300: 'Missbrauch',
REASON_301: 'Erwachseneninhalte',
REASON_302: 'Drogenwerbung',
REASON_303: 'Kinderpornographie',
REASON_304: 'Gewalt / Extremismus',

// Notifications
like: 'liked your post.',
subscribe: 'subscribed to your updates.',
post: 'published a new post.',

// Post Categories
news: 'Nachrichten',
discount: 'Rabatt',
special: 'Spezial',
sales: 'Verkauf',
hires: 'Vermietungen',
events: 'Veranstaltungen',
services: 'Dienstleistungen'

//  Endregion
};
