module.exports = {
	//  Categories localization region
	CATEGORY_100: 'Bars and Restaurants',
	CATEGORY_101: 'Bars',
	CATEGORY_102: 'Billiard clubs',
	CATEGORY_103: 'Night Clubs',
	CATEGORY_104: 'Pubs, beer gardens',
	CATEGORY_105: 'Rock clubs',
	CATEGORY_106: 'Dance clubs',
	CATEGORY_107: 'Karaoke clubs',
	CATEGORY_200: 'Shopping',
	CATEGORY_201: 'Interior decorations',
	CATEGORY_202: 'Bookstores',
	CATEGORY_203: 'Shops toys',
	CATEGORY_204: 'Children clothes shops',
	CATEGORY_205: 'Shopping for pregnant women',
	CATEGORY_206: 'Carpet Stores',
	CATEGORY_207: 'Shops computers',
	CATEGORY_208: 'Shops of cosmetics and perfume',
	CATEGORY_209: 'Furniture Shops',
	CATEGORY_210: 'Musical Instruments Shops',
	CATEGORY_211: 'Underwear shops',
	CATEGORY_212: 'Footwear shops',
	CATEGORY_213: 'Clothing Stores',
	CATEGORY_214: 'Gift Shops',
	CATEGORY_215: 'Shops dishes',
	CATEGORY_216: 'World shops',
	CATEGORY_217: 'Shopping bags',
	CATEGORY_218: 'Drapery',
	CATEGORY_219: 'Camera stores',
	CATEGORY_220: 'Hours Shops',
	CATEGORY_221: 'Electronics stores and household appliances',
	CATEGORY_222: 'Shops for home and garden',
	CATEGORY_223: 'Shops for adults',
	CATEGORY_224: 'Trade klmpleksy',
	CATEGORY_225: 'Jewelry Stores',
	CATEGORY_226: 'Sport shops',
	CATEGORY_300: 'Restaurant and Cafe',
	CATEGORY_301: 'Restaurant',
	CATEGORY_302: 'Antikafe and coworking',
	CATEGORY_303: 'Vegetarian Restaurant',
	CATEGORY_304: 'Kids Cafe',
	CATEGORY_305: 'Fast',
	CATEGORY_306: 'Coffee',
	CATEGORY_307: 'Pizza',
	CATEGORY_308: 'Hookah',
	CATEGORY_309: 'Tea',
	CATEGORY_310: 'Japanese restaurants',
	CATEGORY_311: 'Cafe',
	CATEGORY_400: 'Entertainment, recreation',
	CATEGORY_401: 'Circus',
	CATEGORY_402: 'Parks',
	CATEGORY_403: 'Cinema',
	CATEGORY_404: 'Zoos',
	CATEGORY_405: 'Bowling',
	CATEGORY_406: 'Saunas',
	CATEGORY_407: 'Rides',
	CATEGORY_408: 'Water Parks',
	CATEGORY_409: 'Dolphinariums',
	CATEGORY_410: 'Concert Hall',
	CATEGORY_411: 'Beaches',
	CATEGORY_412: 'Dance schools',
	CATEGORY_500: 'Sport and leisure akivny',
	CATEGORY_501: 'Swimming',
	CATEGORY_502: 'Martial Arts',
	CATEGORY_503: 'Riding',
	CATEGORY_504: 'Golf Clubs',
	CATEGORY_505: 'Ski slopes',
	CATEGORY_506: 'Yoga Center',
	CATEGORY_507: 'Fitness Club',
	CATEGORY_508: 'Yacht Club',
	CATEGORY_509: 'Bicycle rental',
	CATEGORY_510: 'Sports section',
	CATEGORY_511: 'Stadiums',
	CATEGORY_512: 'Parachute',
	CATEGORY_513: 'Paintball',
	CATEGORY_514: 'Ice rinks',
	CATEGORY_515: 'Karting',
	CATEGORY_600: 'Repair services',
	CATEGORY_601: 'Computer services',
	CATEGORY_602: 'Repair phones',
	CATEGORY_603: 'Appliance Repair',
	CATEGORY_604: 'Repair of musical instruments',
	CATEGORY_605: 'Shoe Repair',
	CATEGORY_606: 'Repair and plumbing services',
	CATEGORY_607: 'Repair of printers, refilling cartridges',
	CATEGORY_608: 'Repair of TVs',
	CATEGORY_609: 'Repair of cameras',
	CATEGORY_610: 'Watch Repair',
	CATEGORY_611: 'Furniture Restoration',
	CATEGORY_700: 'Auto',
	CATEGORY_701: 'Spare parts and accessories',
	CATEGORY_702: 'Car',
	CATEGORY_703: 'Motor',
	CATEGORY_704: 'Auto tuning',
	CATEGORY_705: 'Schools',
	CATEGORY_706: 'Car Rental',
	CATEGORY_707: 'Tyre',
	CATEGORY_708: 'Tires and wheels',
	CATEGORY_709: 'Evacuation',
	CATEGORY_800: 'Legal Services',
	CATEGORY_801: 'Lawyers, Legal Services',
	CATEGORY_802: 'Notaries',
	CATEGORY_900: 'Health and Beauty',
	CATEGORY_901: 'Other services',
	CATEGORY_902: 'Spa',
	CATEGORY_903: 'Stylists',
	CATEGORY_904: 'Manicure salons',
	CATEGORY_905: 'Massage',
	CATEGORY_906: 'Hair',
	CATEGORY_907: 'Piercing',
	CATEGORY_908: 'Beauty',
	CATEGORY_909: 'Tanning',
	CATEGORY_910: 'Tattoo parlors and piercing',
	CATEGORY_1000: 'Plants, flowers',
	CATEGORY_1001: 'Flower shops',
	CATEGORY_1002: 'Garden centers',
	CATEGORY_1100: 'Animals',
	CATEGORY_1101: 'Veterinary pharmacies',
	CATEGORY_1102: 'Veterinary Clinic',
	CATEGORY_1103: 'Pet',
	CATEGORY_1104: 'List',
	CATEGORY_1105: 'Animal shelters',
	CATEGORY_1106: 'Salons for animals',
	CATEGORY_1200: 'Culture and Art',
	CATEGORY_1201: 'Museum',
	CATEGORY_1202: 'Performing Arts',
	CATEGORY_1203: 'Library',
	CATEGORY_1204: 'Concerts',
	CATEGORY_1205: 'Cinema',
	CATEGORY_1206: 'Music',
	CATEGORY_1300: 'Medical',
	CATEGORY_1301: 'Pharmacy',
	CATEGORY_1302: 'Dentistry',
	CATEGORY_1303: 'Psychologists',
	CATEGORY_1304: 'Medical equipment',
	CATEGORY_1305: 'Private Medical Clinic',
	CATEGORY_1306: 'Diagnostic Center',
	CATEGORY_1307: 'Clinics',
	CATEGORY_1308: 'Hospitals',
	CATEGORY_1309: 'Oriental Medicine',
	CATEGORY_1400: 'Education',
	CATEGORY_1401: 'Universities',
	CATEGORY_1402: 'Colleges',
	CATEGORY_1403: 'Courses',
	CATEGORY_1404: 'Music School',
	CATEGORY_1405: 'Trainings and seminars',
	CATEGORY_1406: 'Art School',
	CATEGORY_1407: 'School',
	CATEGORY_1500: 'Tourism',
	CATEGORY_1501: 'Visa Centers',
	CATEGORY_1502: 'Recreation',
	CATEGORY_1503: 'Tour Operators',
	CATEGORY_1504: 'Travel Agencies',

	// Reports
	REASON_100: 'Pornography',
	REASON_101: 'Spamming',
	REASON_102: 'Abusive conduct',
	REASON_200: 'Abuse',
	REASON_201: 'Materials for adults',
	REASON_202: 'Drugs promotion',
	REASON_203: 'Child pornography',
	REASON_204: 'Violence / extremism',
	REASON_300: 'Abuse',
	REASON_301: 'Materials for adults',
	REASON_302: 'Drugs promotion',
	REASON_303: 'Child pornography',
	REASON_304: 'Violence / extremism',

	// Notifications
	like: 'liked your post.',
	subscribe: 'subscribed to your updates.',
	post: 'published a new post.',

	// Post Categories
	news: 'news',
	discount: 'discount',
	special: 'special',
	sales: 'sales',
	hires: 'hires',
	events: 'events',
	services: 'services'

	//  Endregion
};
